/**
 * Campaign Milestone Model (CA-19)
 * Records milestone celebrations for a campaign.
 *
 * Milestones are created automatically when funding/sharing/prayer meters cross
 * configured thresholds (e.g. 25%, 50%, 75%, 100% of goal), and can also be
 * created manually by the campaign creator (custom milestones).
 */

const mongoose = require('mongoose');

const campaignMilestoneSchema = new mongoose.Schema(
  {
    milestone_id: {
      type: String,
      required: [true, 'Milestone ID is required'],
      unique: true,
      index: true,
    },

    campaign_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Campaign',
      required: [true, 'Campaign ID is required'],
      index: true,
    },

    // What kind of meter triggered this milestone
    meter_type: {
      type: String,
      enum: ['funding', 'sharing', 'prayer', 'donors', 'custom'],
      default: 'funding',
      index: true,
    },

    // Auto milestones: the percentage threshold reached (25/50/75/100, etc.)
    percentage: {
      type: Number,
      min: 0,
      max: 1000,
    },

    // Snapshot of the meter at the moment the milestone was reached
    value_at_reached: {
      type: Number, // cents for funding, count otherwise
      default: 0,
    },
    goal_at_reached: {
      type: Number,
      default: 0,
    },

    title: {
      type: String,
      required: true,
      maxlength: 200,
      trim: true,
    },
    message: {
      type: String,
      maxlength: 1000,
      trim: true,
    },

    // Whether this was auto-generated by the system or added by the creator
    source: {
      type: String,
      enum: ['auto', 'manual'],
      default: 'auto',
      index: true,
    },

    // Celebration display state
    celebration_emoji: {
      type: String,
      maxlength: 16,
      default: '🎉',
    },
    is_celebrated: {
      type: Boolean,
      default: true,
    },

    reached_at: {
      type: Date,
      default: () => new Date(),
      index: true,
    },
    created_at: {
      type: Date,
      default: () => new Date(),
    },
  },
  {
    collection: 'campaign_milestones',
    timestamps: false,
  }
);

// A given auto percentage milestone for a meter should only exist once per campaign
campaignMilestoneSchema.index(
  { campaign_id: 1, meter_type: 1, percentage: 1, source: 1 },
  {
    unique: true,
    partialFilterExpression: { source: 'auto' },
  }
);
campaignMilestoneSchema.index({ campaign_id: 1, reached_at: -1 });

module.exports = mongoose.model('CampaignMilestone', campaignMilestoneSchema);
