/**
 * Message Model
 * Individual message within a Conversation.
 *
 * Supports text bodies, attachments, per-user soft deletes, edit history,
 * read/delivery tracking, and system-generated messages (e.g. context events
 * like "Volunteer offer accepted").
 */

const mongoose = require('mongoose');
const { nanoid } = require('nanoid');

const attachmentSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    type: {
      type: String,
      enum: ['image', 'file', 'video', 'audio'],
      default: 'file',
    },
    name: { type: String, default: null },
    size_bytes: { type: Number, default: null },
  },
  { _id: false }
);

const messageSchema = new mongoose.Schema(
  {
    message_id: {
      type: String,
      unique: true,
      index: true,
    },

    conversation_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Conversation',
      required: true,
      index: true,
    },

    sender_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    // Denormalized recipient for fast "my unread" queries on a 1:1 thread
    recipient_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    body: {
      type: String,
      maxlength: 5000,
      default: '',
    },

    attachments: {
      type: [attachmentSchema],
      default: [],
    },

    // System messages are generated by the platform, not typed by a user
    is_system: {
      type: Boolean,
      default: false,
    },

    // Delivery / read tracking
    delivered: {
      type: Boolean,
      default: false,
    },
    delivered_at: {
      type: Date,
      default: null,
    },
    read: {
      type: Boolean,
      default: false,
      index: true,
    },
    read_at: {
      type: Date,
      default: null,
    },

    // Edit tracking
    edited: {
      type: Boolean,
      default: false,
    },
    edited_at: {
      type: Date,
      default: null,
    },

    // Per-user soft delete: users who have hidden this message for themselves
    deleted_for: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
    // Hard delete flag (deleted for everyone, e.g. moderation/sender removal)
    is_deleted: {
      type: Boolean,
      default: false,
      index: true,
    },
    deleted_at: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

/**
 * Indexes for efficient querying
 */
messageSchema.index({ conversation_id: 1, created_at: -1 });
messageSchema.index({ recipient_id: 1, read: 1 });
messageSchema.index({ sender_id: 1, created_at: -1 });

/**
 * Pre-validate hook: generate a human-readable message_id.
 */
messageSchema.pre('validate', function preValidate(next) {
  if (!this.message_id) {
    this.message_id = `MSG-${nanoid(18)}`;
  }
  next();
});

/**
 * Pre-save hook: keep timestamps consistent for read/edit transitions.
 */
messageSchema.pre('save', function preSave(next) {
  if (this.isModified('read') && this.read && !this.read_at) {
    this.read_at = new Date();
  }
  if (this.isModified('delivered') && this.delivered && !this.delivered_at) {
    this.delivered_at = new Date();
  }
  next();
});

/**
 * Whether this message has been hidden for a given user.
 * @param {string} userId
 * @returns {boolean}
 */
messageSchema.methods.isHiddenFor = function isHiddenFor(userId) {
  if (this.is_deleted) return true;
  return this.deleted_for.some((id) => id.toString() === userId.toString());
};

module.exports = mongoose.model('Message', messageSchema);
